from typing import List

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import get_current_user
from app.database import get_db
from app.models import User
from app.schemas.quiz import (
    QuizAttemptRequest,
    QuizAttemptResponse,
    QuizGenerateRequest,
    QuizListItem,
    QuizResponse,
)
from app.services import quiz_service

router = APIRouter(prefix="/quiz", tags=["quiz"])


@router.post("/generate", response_model=QuizResponse, status_code=201)
async def generate_quiz(
    body: QuizGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Generate a quiz or flashcard set from a document using Gemini AI.
    The document must belong to the requesting user and have status "completed".
    Generation typically takes 5-15 seconds depending on document length.
    """
    return await quiz_service.generate_quiz(
        db, body.document_id, body.quiz_type, body.count, current_user
    )


@router.get("", response_model=List[QuizListItem])
async def list_quizzes(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List all quizzes and flashcard sets generated by this user."""
    return await quiz_service.list_quizzes(db, current_user)


@router.get("/{quiz_id}", response_model=QuizResponse)
async def get_quiz(
    quiz_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Retrieve a previously generated quiz with all its items."""
    return await quiz_service.get_quiz(db, quiz_id, current_user)


@router.post("/{quiz_id}/attempt", response_model=QuizAttemptResponse, status_code=201)
async def submit_attempt(
    quiz_id: int,
    body: QuizAttemptRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Submit answers for a quiz and receive a scored result with per-question breakdown.
    For flashcard reviews, send an empty answers list — no score is computed.
    Each answer is the 0-based index of the selected option, or null if skipped.
    """
    return await quiz_service.submit_attempt(db, quiz_id, body.answers, current_user)
