#!/bin/bash
# ──────────────────────────────────────────────────────────────────────────────
# user_data.sh — EC2 first-boot bootstrap script
#
# This script runs ONCE as root when the EC2 instance first starts.
# It is passed to the instance via the user_data field in main.tf.
# Terraform substitutes ${variable} placeholders before sending it to AWS.
#
# After this script completes, DocuBrain is fully running:
#   Nginx (port 80) → FastAPI (port 8000 internal) → PgBouncer → Postgres
#
# You can watch progress:
#   ssh ubuntu@<ip>
#   tail -f /var/log/cloud-init-output.log
#
# If something goes wrong, the full log is at /var/log/user-data.log
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail   # -e: exit on error, -u: error on unset variable, -o pipefail: pipe errors propagate
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1
# ↑ tee: write stdout to both the log file AND the system logger (visible in journalctl)

echo "=== DocuBrain bootstrap started at $(date) ==="


# ── 1. System update ──────────────────────────────────────────────────────────
echo "=== Updating system packages ==="
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \
  curl \
  git \
  ca-certificates \
  gnupg \
  lsb-release \
  awscli        # AWS CLI for debugging S3 access, checking IAM role


# ── 2. Install Docker ─────────────────────────────────────────────────────────
# Use Docker's official apt repository — the Ubuntu default is outdated.
echo "=== Installing Docker ==="
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
  gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -qq
apt-get install -y -qq \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin   # "docker compose" (v2) as a plugin, not standalone docker-compose

# Allow ubuntu user to run Docker without sudo
usermod -aG docker ubuntu

# Start Docker and enable it to start on reboot
systemctl start docker
systemctl enable docker

echo "Docker version: $(docker --version)"


# ── 3. Create app directory and write .env ────────────────────────────────────
echo "=== Creating application directory ==="
APP_DIR="/opt/${project_name}"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# Write the .env file with Terraform-substituted values.
# Note: AWS credentials are intentionally ABSENT — the IAM role provides them.
cat > .env << 'ENVFILE'
# Generated by Terraform user_data.sh — do not edit manually
# Changes here are overwritten on instance replacement

# Database
POSTGRES_USER=docubrain
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=docubrain

# App
SECRET_KEY=${secret_key}
ENVIRONMENT=production
FRONTEND_URL=https://${project_name}.yourdomain.com

# AI
GEMINI_API_KEY=${gemini_api_key}
PINECONE_API_KEY=${pinecone_api_key}
PINECONE_INDEX_NAME=${pinecone_index_name}

# S3 — no AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY
# The EC2 IAM role provides temporary credentials automatically via IMDS.
# The SDK (boto3/minio) picks them up from http://169.254.169.254/latest/meta-data/iam/
S3_BUCKET_NAME=${s3_bucket_name}
AWS_REGION=${aws_region}
S3_ENDPOINT=

# CORS — update after DNS is configured
CORS_ALLOWED_ORIGINS=https://${project_name}.yourdomain.com,http://localhost:5173
ENVFILE

chmod 600 .env   # only root can read — contains secrets


# ── 4. Clone the repository ───────────────────────────────────────────────────
echo "=== Cloning DocuBrain repository ==="
# Replace with your actual GitHub repo URL
git clone https://github.com/YOUR_USERNAME/docubrain.git "$APP_DIR/repo" || {
  echo "WARNING: git clone failed — you may need to set up deploy keys for a private repo"
  echo "Continuing with a placeholder — manually git clone later"
  mkdir -p "$APP_DIR/repo"
}

# Copy .env where docker-compose expects it
cp .env "$APP_DIR/repo/.env" 2>/dev/null || true


# ── 5. Create a Docker network ────────────────────────────────────────────────
# Services communicate over this named network.
# The CI/CD deploy script references it when starting new containers.
docker network create docubrain_network 2>/dev/null || true
# "|| true" — ignore the error if the network already exists (e.g. on re-runs)


# ── 6. Start the stack ────────────────────────────────────────────────────────
echo "=== Starting DocuBrain stack ==="
if [ -f "$APP_DIR/repo/docker-compose.yml" ]; then
  cd "$APP_DIR/repo"
  docker compose --env-file .env up -d --build
  echo "=== Stack started. Checking health in 30s... ==="
  sleep 30
  docker compose ps
else
  echo "WARNING: docker-compose.yml not found — skipping auto-start"
  echo "SSH in and run: cd $APP_DIR/repo && docker compose up -d"
fi


# ── 7. Set up log rotation ────────────────────────────────────────────────────
# Docker container logs accumulate indefinitely. Without rotation,
# /var/lib/docker/containers/*/json.log can fill the disk in weeks.
cat > /etc/docker/daemon.json << 'DAEMON'
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  }
}
DAEMON
systemctl restart docker


echo "=== DocuBrain bootstrap complete at $(date) ==="
echo "=== Server IP: $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4) ==="
echo "=== Next: SSH in and run: sudo docker ps ==="
